### ISSUE TITLE
Please stop...

### ISSUE THREAD

**Issue by EddyTheLegoGuy** [LUNIServer/UniverseServer#32]
I understand that you want to remake it so bad but please stop making your development Open-Source because people are going to keep asking questions or something worst. Stay Closed-Source until it's perfect for release.

**Comment by Xiphoseer** [comment]
I appreciate that advice but I would advise you to look at the date of last commit to this repository. I am the one who made this version public and have since experienced why it was a bad idea. I can assure you that most past progress has already not been disclosed, and any current efforts from different people are effectively closed source

**Comment by EddyTheLegoGuy** [comment]
Xiphoseer, can you also close all the issues and pull requests since they are not needed. Thanks for the response.
